# Change these first
owner: ajaxsys # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  # - name: BB1
  #  url: https://bb1.biobeone.com/newList
  - name: T7
    url: https://www.trip7.co.jp/api/hotel_company/get/1
  - name: CNPK
    url: https://www.conepoke.com/api/Commodity/count/all
  - name: OT Test
   url: $OT_TEST
  - name: OT Prod
   url: $OT_PRODUCTION
  # - name: Test Secret Site
  #  url: $MY_SECRET_SITE_1

assignees: # Users to assign downtime issues (optional)
  - ajaxsys
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Ajaxsys Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 */12 * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
